backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/products/products.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: Section1, name: section1, widget: object, fields: [
              {label: HeroHeading1, name: heroHeading1, widget: string},
              {label: HeroHeading2, name: heroHeading2, widget: string},
              {label: HeroHeading3, name: heroHeading3, widget: string},
              {label: Description1, name: description1, widget: text},
              {label: donationText1, name: donationText1, widget: text},
              {label: donationText2, name: donationText2, widget: text},
              {label: DonateCTAText, name: donateCTAtext, widget: string},
              {label: BackgroundImage, name: backgroundImage, widget: image},
            ]}
          - {label: Section2, name: section2, widget: object, fields: [
              {label: Section, name: section, widget: string},
              {label: Reason1, name: reason1, widget: object, fields: [
                {label: Belief, name: belief, widget: string },
                {label: Description1, name: description1, widget: text},
                {label: Description2, name: description2, widget: text}
              ]},
              {label: Reason2, name: reason2, widget: object, fields: [
                {label: Belief, name: belief, widget: string },
                {label: Description1, name: description1, widget: text},
                {label: Description2, name: description2, widget: text}
              ]},
              {label: Reason2, name: reason3, widget: object, fields: [
                {label: Belief, name: belief, widget: string },
                {label: Description1, name: description1, widget: text},
                {label: Description2, name: description2, widget: text}
              ]}
            ]}
          - {label: Section3, name: section3, widget: object, fields: [
              {label: Section, name: section, widget: string},
              {label: Content, name: content, widget: object, fields: [
                {label: Content1, name: content1, widget: text },
                {label: Content2, name: content2, widget: text},
                {label: Goal1, name: goal1, widget: text},
                {label: Goal2, name: goal2, widget: text},
                {label: Goal3, name: goal3, widget: text}
              ]},
              {label: ctaText, name: ctaText, widget: string}
            ]}
          - {label: Section4, name: section4, widget: object, fields: [
              {label: Section, name: section, widget: string},
              {label: Content, name: content, widget: text },
              {label: DonateCTAText, name: donateCTAtext, widget: string},
              {label: LearnMoreCTAText, name: learnMoreCTAText, widget: string}
            ]}
          - {label: Section5, name: section5, widget: object, fields: [
              {label: Section, name: section, widget: string},
              {label: content, name: content, widget: object, fields: [
                {label: Sponsor1, name: sponsor1, widget: object, fields: [
                  {label: Name, name: name, widget: string},
                  {label: Image, name: image, widget: image},
                  {label: Description1, name: description1, widget: text}
                ]}, 
                {label: Sponsor2, name: sponsor2, widget: object, fields: [
                  {label: Name, name: name, widget: string},
                  {label: Image, name: image, widget: image},
                  {label: Description1, name: description1, widget: text}
                ]}, 
                {label: Sponsor3, name: sponsor3, widget: object, fields: [
                  {label: Name, name: name, widget: string},
                  {label: Image, name: image, widget: image},
                  {label: Description1, name: description1, widget: text}
                ]}, 
              ]},
              {label: SponsorCTAText, name: sponsorCTAText, widget: string}
            ]}
      - file: "src/pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: Section1, name: section1, widget: object, fields: [
              {label: Heading1, name: heading1, widget: string},
              {label: Description1, name: description1, widget: text}
          ]}
          - {label: Section2, name: section2, widget: object, fields: [
              {label: Section, name: section, widget: string},
              {label: Definition1, name: definition1, widget: text},
              {label: Definition2, name: definition2, widget: text},
              {label: Source, name: source, widget: string}
            ]}
          - {label: Section3, name: section3, widget: object, fields: [
              {label: Section, name: section, widget: string},
              {label: Belief1, name: belief1, widget: object, fields: [
                {label: Heading, name: heading, widget: text}
                {label: Description, name: description, widget: text}
              ]},
              {label: Belief2, name: belief2, widget: object, fields: [
                {label: Heading, name: heading, widget: text}
                {label: Description, name: description, widget: text}
              ]},
              {label: Belief3, name: belief3, widget: object, fields: [
                {label: Heading, name: heading, widget: text}
                {label: Description, name: description, widget: text}
              ]},
            ]}
          - {label: Section4, name: section4, widget: object, fields: [
              {label: Section, name: section, widget: string},
              {label: Director1, name: director1, widget: object, fields: [
                {label: Name, name: name, widget: string},
                {label: Image, name: image, widget: image},
                {label: Description1, name: description, widget: text}
              ]}, 
              {label: Director2, name: director2, widget: object, fields: [
                {label: Name, name: name, widget: string},
                {label: Image, name: image, widget: image},
                {label: Description1, name: description, widget: text}
              ]},
              {label: Director3, name: director3, widget: object, fields: [
                {label: Name, name: name, widget: string},
                {label: Image, name: image, widget: image},
                {label: Description, name: description, widget: text}
              ]},
              {label: Director4, name: director4, widget: object, fields: [
                {label: Name, name: name, widget: string},
                {label: Image, name: image, widget: image},
                {label: Description1, name: description, widget: text}
              ]},
              {label: Director5, name: director5, widget: object, fields: [
                {label: Name, name: name, widget: string},
                {label: Image, name: image, widget: image},
                {label: Description1, name: description, widget: text}
              ]}
            ]}
      - file: "src/pages/donate.md"
        label: "Donate Page"
        name: "donate"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "donate-page"}
          - {label: Heading1, name: heading1, widget: string}
          - {label: Description, name: description, widget: text}
          - {label: Description2, name: description2, widget: string}
          - {label: Benefits, name: benefits, widget: object, fields: [
              {label: BenefitTitle, name: benefitTitle, widget: string},
              {label: Benefit1, name: benefit1, widget: object, fields: [
                {label: Title, name: title, widget: string },
                {label: Description, name: description, widget: text},
              ]},
              {label: Benefit2, name: benefit2, widget: object, fields: [
                {label: Title, name: title, widget: string },
                {label: Description, name: description, widget: text},
              ]},
              {label: Benefit3, name: benefit3, widget: object, fields: [
                {label: Title, name: title, widget: string },
                {label: Description, name: description, widget: text},
              ]}
            ]}

          
# - file: "src/pages/about/index.md"
#   label: "About"
#   name: "about"
#   fields:
#     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
#     - {label: "Title", name: "title", widget: "string"}
#     - {label: "Body", name: "body", widget: "markdown"}
          # - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image, name: image, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          # - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          # - {label: Full_image, name: full_image, widget: image}
          # - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
